title: Hello, world! I'm Akansh Maurya
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Akansh Maurya # add your name
author-img: akansh_maurya.jpg # add your photo
about-author: I am a student pursuing electrical engineering, intrested in Deep Learing, Robotics, and control systems. # add description
social-twitter: akansh_maurya # add your Twitter handle
social-facebook: akansh.maurya # add your Facebook handle
social-github: akansh12 # add your Github handle
social-linkedin: akansh-maurya-246570154 # add your Linkedin handle
social-email: akanshmaurya@gmail.com # add your Email address

# Disqus
discus-identifier: akansh-maurya  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
